name: Build and push image in docker registry
description: Action to running the application tests

outputs:
  tag:
    description: "Image tag"
    value: ${{ steps.image_tag.outputs.tag }}

inputs:
  repository_name:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate image tag
      id: image_tag
      run: echo "tag=hello" >> $GITHUB_OUTPUT
      shell: bash