name: Build and push image in docker registry
description: Action to running the application tests

outputs:
  tag:
    description: "Image tag"
    value: ${{ steps.image_tag.outputs.tag }}
  repo_name:
    description: "Repository name without a organization"
    value: ${{ steps.repo_name.outputs.repo }}

inputs:
  docker_user:
    description: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Get the repository name 
      id: repo_name
      shell: bash
      run: |
        REPO_NAME=${{ github.repository }}
        echo "repo=${REPO_NAME#*/}" >> $GITHUB_OUTPUT
    
    - name: Mounting the image tag
      id: image_tag
      shell: bash
      run: | 
        TAG=${{ github.sha }}

        IMAGE_TAG="${{ inputs.docker_user }}/${{ steps.repo_name.outputs.repo }}:$TAG"

        echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
