name: Node workflow CI
description: This workflow is used to a Node.js projects

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout branch 
          uses: actions/checkout@v4
        
        - name: Setup node in the host
          uses: actions/setup-node@v4
          with:
           node-version: 22.x

        - name: Running the application tests 
          uses: ../actions/tests/action.yaml
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from gustavo-studies organization
