name: Python workflow CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout branch 
          uses: actions/checkout@v4
        
        - name: Setup Python in the host
          uses: actions/setup-python@v5
          with:
           python-version: 3.x
        
        - name: Install application dependencies
          run: pip install -r requirements.txt

        - name: Running the application tests 
          uses: gustavo-studies-devops/github-pipeline/.github/actions/tests@develop
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from gustavo-studies organization
