name: Python workflow CI

on:
  workflow_call:
    inputs:
        environment:
            type: string
            required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Python in the host
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Running the application tests
        uses: gustavo-studies-devops/github-pipeline/.github/actions/tests@develop

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    outputs:
      tag: ${{ steps.image_tag.outputs.tag }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image tag
        id: image_tag
        uses: gustavo-studies-devops/github-pipeline/.github/actions/generate_image_tag@develop
        with:
          docker_user: ${{ vars.DOCKER_USERNAME }}
          env: ${{ inputs.environment }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.image_tag.outputs.tag }}
