name: Python workflow CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Python in the host
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Running the application tests
        uses: gustavo-studies-devops/github-pipeline/.github/actions/tests@develop

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and push in registry
        id: image-tag
        uses: gustavo-studies-devops/github-pipeline/.github/actions/build_push@develop

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{vars.DOCKER_USERNAME}}/app:${{ steps.image-tag.outputs.tag }}
